name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_introduction: yes
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_details: lines
          plugin_languages_sections: most-used
          plugin_languages_recent_load: 3
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          commits_authoring: kyan0045@users.noreply.github.com
